apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    inference.networking.k8s.io/bundle-version: v1.1.0
  name: inferenceobjectives.inference.networking.x-k8s.io
spec:
  group: inference.networking.x-k8s.io
  names:
    kind: InferenceObjective
    listKind: InferenceObjectiveList
    plural: inferenceobjectives
    singular: inferenceobjective
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.poolRef.name
      name: Inference Pool
      type: string
    - jsonPath: .spec.priority
      name: Priority
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: InferenceObjective is the Schema for the InferenceObjectives
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: |-
              InferenceObjectiveSpec represents the desired state of a specific model use case. This resource is
              managed by the "Inference Workload Owner" persona.

              The Inference Workload Owner persona is someone that trains, verifies, and
              leverages a large language model from a model frontend, drives the lifecycle
              and rollout of new versions of those models, and defines the specific
              performance and latency goals for the model. These workloads are
              expected to operate within an InferencePool sharing compute capacity with other
              InferenceObjectives, defined by the Inference Platform Admin.
            properties:
              poolRef:
                description: PoolRef is a reference to the inference pool, the pool
                  must exist in the same namespace.
                properties:
                  group:
                    default: inference.networking.k8s.io
                    description: Group is the group of the referent.
                    maxLength: 253
                    pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                    type: string
                  kind:
                    default: InferencePool
                    description: Kind is kind of the referent. For example "InferencePool".
                    maxLength: 63
                    minLength: 1
                    pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                    type: string
                  name:
                    description: Name is the name of the referent.
                    maxLength: 253
                    minLength: 1
                    type: string
                required:
                - name
                type: object
              priority:
                description: |-
                  Priority defines how important it is to serve the request compared to other requests in the same pool.
                  Priority is an integer value that defines the priority of the request.
                  The higher the value, the more critical the request is; negative values _are_ allowed.
                  No default value is set for this field, allowing for future additions of new fields that may 'one of' with this field.
                  However, implementations that consume this field (such as the Endpoint Picker) will treat an unset value as '0'.
                  Priority is used in flow control, primarily in the event of resource scarcity(requests need to be queued).
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
