apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: kv-cache-policy
  namespace: default
spec:
  default:
    balancingMode: CUSTOM_METRICS
    customMetrics:
    - name: gke.named_metrics.kv-cache
      dryRun: false
    trafficDuration: LONG
  targetRef:
    group: networking.gke.io
    kind: GCPInferencePoolImport
    name: inference-pool
