apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: inference-health-check
  namespace: default
spec:
  default:
    config:
      httpHealthCheck:
        port: 8080
        requestPath: /
      type: HTTP
  targetRef:
    group: networking.gke.io
    kind: GCPInferencePoolImport
    name: inference-pool
