apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: inference-pool
  namespace: default
spec:
  selector:
    matchLabels:
      app: inference-server
  endpointPickerRef:
    name: inference-picker
    kind: Service
    port:
      number: 8080
  targetPorts:
  - number: 8080
